// <auto-generated />
namespace UsersLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Logs_Improve : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Logs_Improve));
        
        string IMigrationMetadata.Id
        {
            get { return "201709031128001_Logs_Improve"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
